version: '3.9'  # Compose 文件版本

services:
  db:  # 定义数据库服务
    image: mysql:8.0  # 使用官方 MySQL 8.0 镜像
    container_name: wordpress-db  # 容器名字
    restart: unless-stopped  # 容器异常停止自动重启
    environment:  # 环境变量
      MYSQL_ROOT_PASSWORD: rootpassword  # root 用户密码
      MYSQL_DATABASE: wordpress  # 创建的数据库名
      MYSQL_USER: wpuser  # 普通用户
      MYSQL_PASSWORD: wppassword  # 普通用户密码
    volumes:
      - db_data:/var/lib/mysql  # 数据卷，持久化数据库

  wordpress:  # 定义 WordPress 服务
    image: wordpress:latest  # 使用官方 WordPress 镜像
    container_name: wordpress-app
    restart: unless-stopped
    ports:
      - "8080:80"  # 将宿主机 8080 端口映射到容器 80 端口
    environment:
      WORDPRESS_DB_HOST: db:3306  # 数据库服务地址和端口
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html  # 持久化 WordPress 文件

volumes:  # 定义数据卷
  db_data:
  wp_data:
